# https://blog.streamlit.io/streamlit-authenticator-part-1-adding-an-authentication-component-to-your-app/

credentials:
  usernames:
    admin:
      email: anujkr98110@gmail.com
      name: A. K. Sharma
      city: Mohali
      area: Punjab
      role: Admin
      password: '$2b$12$lMxdoCqZBDUoWEZ0C6xhwOfQqywSIeJEH1l2trkulvjWLC86WGCd2' # abc
cookie:
  expiry_days: 1
  key: a8f3d2e1b9c7f4a0e5d6c3b2a1f8e7d4c9b0a3f2e1d8c7b6a5f4e3d2c1b0a9
  name: random_cookie_name
preauthorized:
  emails:
  - anujkr98110@gmail.com